// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8APVpE0IKphyyhQ7V8UYmz9LJfa9xdAc',
    appId: '1:69911528623:web:df7dcff213ec1622bbc05a',
    messagingSenderId: '69911528623',
    projectId: 'my-video-call-agora',
    authDomain: 'my-video-call-agora.firebaseapp.com',
    storageBucket: 'my-video-call-agora.appspot.com',
    measurementId: 'G-4C3M6122FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbbNrzsFD13IwgcCkFe4t_t1are4jmn0',
    appId: '1:69911528623:android:9d1fe678d5ab8f4cbbc05a',
    messagingSenderId: '69911528623',
    projectId: 'my-video-call-agora',
    storageBucket: 'my-video-call-agora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBklPf0NrPtAXpyulHDkekhShdtK-aqEhM',
    appId: '1:69911528623:ios:07600b76fb117e7fbbc05a',
    messagingSenderId: '69911528623',
    projectId: 'my-video-call-agora',
    storageBucket: 'my-video-call-agora.appspot.com',
    iosBundleId: 'com.example.myVideoCallAgora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBklPf0NrPtAXpyulHDkekhShdtK-aqEhM',
    appId: '1:69911528623:ios:e978bc03063d59d6bbc05a',
    messagingSenderId: '69911528623',
    projectId: 'my-video-call-agora',
    storageBucket: 'my-video-call-agora.appspot.com',
    iosBundleId: 'com.example.myVideoCallAgora.RunnerTests',
  );
}
